### ISSUE TITLE
Closing js tag not working

### ISSUE THREAD

**Issue by gercobrandwijk** [iuyoy/highlight-string-code#1]
It looks like the end tag for javascript highlighting (!js) is not working correctly. 

See this screenshot:
![image](https://user-images.githubusercontent.com/6197958/71576552-4917c180-2af1-11ea-8818-85394d70c81f.png)

**Comment by iuyoy** [comment]
Confirmed, thank you for pointing that, I will add SPACE in pattern in next version.

**Comment by gercobrandwijk** [comment]
Are you saying that it is because of the space between // and !js? Actually that's not the problem, because also with that space, it is still not working:
![image](https://user-images.githubusercontent.com/6197958/71621921-96b82b00-2bd2-11ea-92cc-6ea45fd12141.png)

**Comment by iuyoy** [comment]
I mean the spaces in front of //!js.

**Comment by gercobrandwijk** [comment]
Thanks for your reply. with //!js at the beginning of the line it is working indeed! I assume that you will also implement this for they other selectors?

**Comment by iuyoy** [comment]
Yes, I should check all patterns. Thank you for your suggestions.

**Comment by iuyoy** [comment]
Fixed in v0.4.4.
