### ISSUE TITLE
Broken highlight for go language

### ISSUE THREAD

**Issue by Dancheg97** [iuyoy/highlight-string-code#12]
Code highlight was broken after installing this extension:

With extension:

![image](https://user-images.githubusercontent.com/58640116/162568418-a6446b16-9b6e-46eb-9cb9-2c88295fe43e.png)

Without extension:

![image](https://user-images.githubusercontent.com/58640116/162568450-89ec53ea-99e5-4000-b40a-84160d7dfaf9.png)

**Comment by iuyoy** [comment]
@Dancheg97, the highlight starts with UPPERCASE keyword should have a `; ` at the end of the query.
![image](https://user-images.githubusercontent.com/11738832/163750862-4e617317-daa6-4883-b54d-6dd41f94cff2.png)
