### ISSUE TITLE
User-custom tags and languages

### ISSUE THREAD

**Issue by rmccampbell** [iuyoy/highlight-string-code#13]
Would it be possible to make the set of tags and languages user configurable? I'm interested in for example supporting GLSL shader code in string literals, e.g. `//glsl`, `//!glsl`.

Also for C++ raw string literal tags could be used as language tags. For example
```
R"sql(
SELECT * FROM ...;
)sql"
```
(Google's internal fork of VS Code supports the latter feature)

**Comment by iuyoy** [comment]
It is hard to add configurable rules which is explained in issue #4.
You can fork this repo to implement your own highlight methods, or directly change the extension rule file follow the method in above issue link.
