### ISSUE TITLE
it doesn't recognize the parentheses very well.

### ISSUE THREAD

**Issue by hankaul** [iuyoy/highlight-string-code#14]
![image](https://user-images.githubusercontent.com/100248974/224470644-68022760-79be-4213-b5e3-1bbf1a6a3056.png)
![image](https://user-images.githubusercontent.com/100248974/224470649-fbf5d960-d7ee-448a-9be4-248a180034ec.png)

Is there any way I can fix this?

**Comment by iuyoy** [comment]
Duplicate with #11, and you can find more information in #6 and #4
