### ISSUE TITLE
Highlighting with uppercase doesn't work when there are spaces between the opening string and the uppercase

### ISSUE THREAD

**Issue by sergei3000** [iuyoy/highlight-string-code#16]
<img width="193" alt="image" src="https://github.com/iuyoy/highlight-string-code/assets/18502517/502b0d33-07a2-4083-96a7-9e8c7eeee694">

<img width="186" alt="image" src="https://github.com/iuyoy/highlight-string-code/assets/18502517/3cb1b4da-91dd-4f76-ba7e-ca5808607675">

The real problem is that when I open a string with `f"""` and start the query text on the next line, I do so with indentation consisting of spaces which turns off highlighting.

**Comment by stianthaulow** [comment]
The regex for matching SQL lines based on SQL keywords is in line 168 in [syntaxes/highlight-string-code.json](https://github.com/iuyoy/highlight-string-code/blob/1c4784557db907ca405b16e855c1dcdd8f76dcc8/syntaxes/highlight-string-code.json#L168C29-L168C109)

If you find your vscode extensions folder (usually `~/.vscode/extensions`) and edit it there

`iuyoy.highlight-string-code-0.4.5/syntaxes/highlight-string-code.json`

Add `\\s*` at the start of the regex to ignore whitespace.

```json
"begin": "\\s*(SELECT|INSERT|DELETE|UPDATE|DROP|ALTER|CREATE|SET|TRUNCATE|GRANT|REVOKE)\\s",
```
