### ISSUE TITLE
Autocompletion

### ISSUE THREAD

**Issue by moshfeu** [iuyoy/highlight-string-code#2]
Thanks for this extension!

I know that the name of the extension is **highlight**, but it would VERY useful if it would also provide autocompletion. Like https://github.com/styled-components/vscode-styled-components does.

**Comment by iuyoy** [comment]
Hi Mosh, I am glad to receive your feedback. I was intended to add this feature when I built this extension, however, it seems not easy for embedded languages at that time. 

Now, I find that VSCode adds more supports on embedded language, which may make it possible. I will try to implement it.

**Comment by moshfeu** [comment]
Thanks!

My case is for Custom Web Component, because the "official" way to inject css is by strings.
Maybe you can give it as an example in an hypothetical docs' section "Typical usages" to grab some traffic from search engines :)

**Comment by iuyoy** [comment]
This issue will be closed, as I am trying to build a new extension called [Power-Embedded-Langs](https://github.com/iuyoy/Power-Embedded-Langs) to support more language features for embedded languages. The new extension supports basic auto-completion and hove prompt now. 

It is still under development and not published to VSCode marketplace. You can try this extension by installing the current pre-release vsix at [here](https://github.com/iuyoy/Power-Embedded-Langs/releases). If you have any question, please feel free to open issues on that repo.

**Comment by moshfeu** [comment]
Thanks.
I just downloaded and tried it but probably I'm missing something.

Here is the code I've added into a .js file.

```
// *js.*
const script = `
  const bar = 8;
  for (let i = 0; i < ba)
`;
// *!js.*
```
I'd expect to get autocomplete for `ba` as `bar` but nothing.
Also, there is no highlight.

**Comment by iuyoy** [comment]
Oh, the sign pairs in the doc are raw regex patterns. So the signs should be `// js` and `// !js` in code. 

I will make the doc more clear in next update.

**Comment by moshfeu** [comment]
Nice! It is working.
But notice that it's not a "real" autocomplete but the ["Words autocomplete"](https://code.visualstudio.com/docs/editor/intellisense#_types-of-completions).

![Screen Shot 2020-07-27 at 9 48 40](https://user-images.githubusercontent.com/3723951/88512646-914b8380-cfef-11ea-8055-06cb9ecc6cfb.png)

compared to

![Screen Shot 2020-07-27 at 9 57 37](https://user-images.githubusercontent.com/3723951/88512695-a0323600-cfef-11ea-95b0-0e45f4f8c188.png)

**Comment by iuyoy** [comment]
You are right. It is one of the reasons why I call it basic support for auto-completion.
