### ISSUE TITLE
The highlight doesn't work for *.ipynb files in jupyter

### ISSUE THREAD

**Issue by weishenl6y6n** [iuyoy/highlight-string-code#3]
Can u make it work for jupyter

**Comment by iuyoy** [comment]
I am not sure if it can run over jupyter editor because jupyter editor is a special feature of python extension. I will spend some time to have a look.

**Comment by iuyoy** [comment]
Hi @weishenl6y6n,
Unfortunately, the current notebook doesn't support the features of highlighting, and  [official notebook API] (https://code.visualstudio.com/api/extension-guides/notebook) says it is still proposed and under development.

An alternative approach is using the [Jupyter code cells](https://code.visualstudio.com/docs/python/jupyter-support-py) in `.py` files.
![image](https://user-images.githubusercontent.com/11738832/97798040-63648380-1c5d-11eb-913c-23e0d754b4b6.png)

**Comment by weishenl6y6n** [comment]
Thank u for telling me these~ @iuyoy

**Comment by iuyoy** [comment]
You are welcome.
